/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KiehnSystemeLoginRouteImport } from './routes/kiehn-systeme-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedServiceCenterRouteImport } from './routes/_authenticated/service-center'
import { Route as AuthenticatedSchluesseluebergabeRouteImport } from './routes/_authenticated/schluesseluebergabe'
import { Route as AuthenticatedSchluesselbuchRouteImport } from './routes/_authenticated/schluesselbuch'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedMonitorRouteImport } from './routes/_authenticated/monitor'
import { Route as AuthenticatedMeineEinsaetzeRouteImport } from './routes/_authenticated/meine-einsaetze'
import { Route as AuthenticatedKundenRouteImport } from './routes/_authenticated/kunden'
import { Route as AuthenticatedIntrahubRouteImport } from './routes/_authenticated/intrahub'
import { Route as AuthenticatedHilfeRouteImport } from './routes/_authenticated/hilfe'
import { Route as AuthenticatedEinsatzErstellenRouteImport } from './routes/_authenticated/einsatz-erstellen'
import { Route as AuthenticatedDienstplaeneRouteImport } from './routes/_authenticated/dienstplaene'
import { Route as AuthenticatedDatenImportRouteImport } from './routes/_authenticated/daten-import'
import { Route as AuthenticatedDateienRouteImport } from './routes/_authenticated/dateien'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlarmierungRouteImport } from './routes/_authenticated/alarmierung'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRevierCenterRouteRouteImport } from './routes/_authenticated/revier-center/route'
import { Route as AuthenticatedRevierCenterIndexRouteImport } from './routes/_authenticated/revier-center/index'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as AuthenticatedNotdienstLutzRouteImport } from './routes/_authenticated/notdienst/lutz'
import { Route as AuthenticatedAbrechnungProviderRouteImport } from './routes/_authenticated/abrechnung.$provider'
import { Route as AuthenticatedRevierCenterOwksRouteRouteImport } from './routes/_authenticated/revier-center/owks/route'
import { Route as AuthenticatedNotdienstRohrserviceRouteRouteImport } from './routes/_authenticated/notdienst/rohrservice/route'
import { Route as AuthenticatedNotdienstBudekoRouteRouteImport } from './routes/_authenticated/notdienst/budeko/route'
import { Route as AuthenticatedRevierCenterOwksIndexRouteImport } from './routes/_authenticated/revier-center/owks/index'
import { Route as AuthenticatedNotdienstRohrserviceIndexRouteImport } from './routes/_authenticated/notdienst/rohrservice/index'
import { Route as AuthenticatedNotdienstBudekoIndexRouteImport } from './routes/_authenticated/notdienst/budeko/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedRevierCenterOwksRundgaengeRouteImport } from './routes/_authenticated/revier-center/owks/rundgaenge'
import { Route as AuthenticatedRevierCenterOwksObjekteRouteImport } from './routes/_authenticated/revier-center/owks/objekte'
import { Route as AuthenticatedRevierCenterOwksNfcPunkteRouteImport } from './routes/_authenticated/revier-center/owks/nfc-punkte'
import { Route as AuthenticatedNotdienstRohrserviceNeuRouteImport } from './routes/_authenticated/notdienst/rohrservice/neu'
import { Route as AuthenticatedNotdienstRohrserviceNachbearbeitungRouteImport } from './routes/_authenticated/notdienst/rohrservice/nachbearbeitung'
import { Route as AuthenticatedNotdienstRohrserviceMitarbeiterRouteImport } from './routes/_authenticated/notdienst/rohrservice/mitarbeiter'
import { Route as AuthenticatedNotdienstBudekoNeuRouteImport } from './routes/_authenticated/notdienst/budeko/neu'
import { Route as AuthenticatedNotdienstBudekoNachbearbeitungRouteImport } from './routes/_authenticated/notdienst/budeko/nachbearbeitung'
import { Route as AuthenticatedNotdienstBudekoMitarbeiterRouteImport } from './routes/_authenticated/notdienst/budeko/mitarbeiter'
import { Route as AuthenticatedAbrechnungProviderVersandRouteImport } from './routes/_authenticated/abrechnung.$provider.versand'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KiehnSystemeLoginRoute = KiehnSystemeLoginRouteImport.update({
  id: '/kiehn-systeme-login',
  path: '/kiehn-systeme-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServiceCenterRoute =
  AuthenticatedServiceCenterRouteImport.update({
    id: '/service-center',
    path: '/service-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchluesseluebergabeRoute =
  AuthenticatedSchluesseluebergabeRouteImport.update({
    id: '/schluesseluebergabe',
    path: '/schluesseluebergabe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchluesselbuchRoute =
  AuthenticatedSchluesselbuchRouteImport.update({
    id: '/schluesselbuch',
    path: '/schluesselbuch',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitorRoute = AuthenticatedMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeineEinsaetzeRoute =
  AuthenticatedMeineEinsaetzeRouteImport.update({
    id: '/meine-einsaetze',
    path: '/meine-einsaetze',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKundenRoute = AuthenticatedKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntrahubRoute = AuthenticatedIntrahubRouteImport.update({
  id: '/intrahub',
  path: '/intrahub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHilfeRoute = AuthenticatedHilfeRouteImport.update({
  id: '/hilfe',
  path: '/hilfe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEinsatzErstellenRoute =
  AuthenticatedEinsatzErstellenRouteImport.update({
    id: '/einsatz-erstellen',
    path: '/einsatz-erstellen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDienstplaeneRoute =
  AuthenticatedDienstplaeneRouteImport.update({
    id: '/dienstplaene',
    path: '/dienstplaene',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatenImportRoute =
  AuthenticatedDatenImportRouteImport.update({
    id: '/daten-import',
    path: '/daten-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDateienRoute = AuthenticatedDateienRouteImport.update({
  id: '/dateien',
  path: '/dateien',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlarmierungRoute =
  AuthenticatedAlarmierungRouteImport.update({
    id: '/alarmierung',
    path: '/alarmierung',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevierCenterRouteRoute =
  AuthenticatedRevierCenterRouteRouteImport.update({
    id: '/revier-center',
    path: '/revier-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevierCenterIndexRoute =
  AuthenticatedRevierCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRevierCenterRouteRoute,
  } as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotdienstLutzRoute =
  AuthenticatedNotdienstLutzRouteImport.update({
    id: '/notdienst/lutz',
    path: '/notdienst/lutz',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAbrechnungProviderRoute =
  AuthenticatedAbrechnungProviderRouteImport.update({
    id: '/abrechnung/$provider',
    path: '/abrechnung/$provider',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevierCenterOwksRouteRoute =
  AuthenticatedRevierCenterOwksRouteRouteImport.update({
    id: '/owks',
    path: '/owks',
    getParentRoute: () => AuthenticatedRevierCenterRouteRoute,
  } as any)
const AuthenticatedNotdienstRohrserviceRouteRoute =
  AuthenticatedNotdienstRohrserviceRouteRouteImport.update({
    id: '/notdienst/rohrservice',
    path: '/notdienst/rohrservice',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotdienstBudekoRouteRoute =
  AuthenticatedNotdienstBudekoRouteRouteImport.update({
    id: '/notdienst/budeko',
    path: '/notdienst/budeko',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevierCenterOwksIndexRoute =
  AuthenticatedRevierCenterOwksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRevierCenterOwksRouteRoute,
  } as any)
const AuthenticatedNotdienstRohrserviceIndexRoute =
  AuthenticatedNotdienstRohrserviceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotdienstRohrserviceRouteRoute,
  } as any)
const AuthenticatedNotdienstBudekoIndexRoute =
  AuthenticatedNotdienstBudekoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotdienstBudekoRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRevierCenterOwksRundgaengeRoute =
  AuthenticatedRevierCenterOwksRundgaengeRouteImport.update({
    id: '/rundgaenge',
    path: '/rundgaenge',
    getParentRoute: () => AuthenticatedRevierCenterOwksRouteRoute,
  } as any)
const AuthenticatedRevierCenterOwksObjekteRoute =
  AuthenticatedRevierCenterOwksObjekteRouteImport.update({
    id: '/objekte',
    path: '/objekte',
    getParentRoute: () => AuthenticatedRevierCenterOwksRouteRoute,
  } as any)
const AuthenticatedRevierCenterOwksNfcPunkteRoute =
  AuthenticatedRevierCenterOwksNfcPunkteRouteImport.update({
    id: '/nfc-punkte',
    path: '/nfc-punkte',
    getParentRoute: () => AuthenticatedRevierCenterOwksRouteRoute,
  } as any)
const AuthenticatedNotdienstRohrserviceNeuRoute =
  AuthenticatedNotdienstRohrserviceNeuRouteImport.update({
    id: '/neu',
    path: '/neu',
    getParentRoute: () => AuthenticatedNotdienstRohrserviceRouteRoute,
  } as any)
const AuthenticatedNotdienstRohrserviceNachbearbeitungRoute =
  AuthenticatedNotdienstRohrserviceNachbearbeitungRouteImport.update({
    id: '/nachbearbeitung',
    path: '/nachbearbeitung',
    getParentRoute: () => AuthenticatedNotdienstRohrserviceRouteRoute,
  } as any)
const AuthenticatedNotdienstRohrserviceMitarbeiterRoute =
  AuthenticatedNotdienstRohrserviceMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AuthenticatedNotdienstRohrserviceRouteRoute,
  } as any)
const AuthenticatedNotdienstBudekoNeuRoute =
  AuthenticatedNotdienstBudekoNeuRouteImport.update({
    id: '/neu',
    path: '/neu',
    getParentRoute: () => AuthenticatedNotdienstBudekoRouteRoute,
  } as any)
const AuthenticatedNotdienstBudekoNachbearbeitungRoute =
  AuthenticatedNotdienstBudekoNachbearbeitungRouteImport.update({
    id: '/nachbearbeitung',
    path: '/nachbearbeitung',
    getParentRoute: () => AuthenticatedNotdienstBudekoRouteRoute,
  } as any)
const AuthenticatedNotdienstBudekoMitarbeiterRoute =
  AuthenticatedNotdienstBudekoMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AuthenticatedNotdienstBudekoRouteRoute,
  } as any)
const AuthenticatedAbrechnungProviderVersandRoute =
  AuthenticatedAbrechnungProviderVersandRouteImport.update({
    id: '/versand',
    path: '/versand',
    getParentRoute: () => AuthenticatedAbrechnungProviderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kiehn-systeme-login': typeof KiehnSystemeLoginRoute
  '/login': typeof LoginRoute
  '/revier-center': typeof AuthenticatedRevierCenterRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/alarmierung': typeof AuthenticatedAlarmierungRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dateien': typeof AuthenticatedDateienRoute
  '/daten-import': typeof AuthenticatedDatenImportRoute
  '/dienstplaene': typeof AuthenticatedDienstplaeneRoute
  '/einsatz-erstellen': typeof AuthenticatedEinsatzErstellenRoute
  '/hilfe': typeof AuthenticatedHilfeRoute
  '/intrahub': typeof AuthenticatedIntrahubRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/meine-einsaetze': typeof AuthenticatedMeineEinsaetzeRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/schluesselbuch': typeof AuthenticatedSchluesselbuchRoute
  '/schluesseluebergabe': typeof AuthenticatedSchluesseluebergabeRoute
  '/service-center': typeof AuthenticatedServiceCenterRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/notdienst/budeko': typeof AuthenticatedNotdienstBudekoRouteRouteWithChildren
  '/notdienst/rohrservice': typeof AuthenticatedNotdienstRohrserviceRouteRouteWithChildren
  '/revier-center/owks': typeof AuthenticatedRevierCenterOwksRouteRouteWithChildren
  '/abrechnung/$provider': typeof AuthenticatedAbrechnungProviderRouteWithChildren
  '/notdienst/lutz': typeof AuthenticatedNotdienstLutzRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/revier-center/': typeof AuthenticatedRevierCenterIndexRoute
  '/abrechnung/$provider/versand': typeof AuthenticatedAbrechnungProviderVersandRoute
  '/notdienst/budeko/mitarbeiter': typeof AuthenticatedNotdienstBudekoMitarbeiterRoute
  '/notdienst/budeko/nachbearbeitung': typeof AuthenticatedNotdienstBudekoNachbearbeitungRoute
  '/notdienst/budeko/neu': typeof AuthenticatedNotdienstBudekoNeuRoute
  '/notdienst/rohrservice/mitarbeiter': typeof AuthenticatedNotdienstRohrserviceMitarbeiterRoute
  '/notdienst/rohrservice/nachbearbeitung': typeof AuthenticatedNotdienstRohrserviceNachbearbeitungRoute
  '/notdienst/rohrservice/neu': typeof AuthenticatedNotdienstRohrserviceNeuRoute
  '/revier-center/owks/nfc-punkte': typeof AuthenticatedRevierCenterOwksNfcPunkteRoute
  '/revier-center/owks/objekte': typeof AuthenticatedRevierCenterOwksObjekteRoute
  '/revier-center/owks/rundgaenge': typeof AuthenticatedRevierCenterOwksRundgaengeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/notdienst/budeko/': typeof AuthenticatedNotdienstBudekoIndexRoute
  '/notdienst/rohrservice/': typeof AuthenticatedNotdienstRohrserviceIndexRoute
  '/revier-center/owks/': typeof AuthenticatedRevierCenterOwksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiehn-systeme-login': typeof KiehnSystemeLoginRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alarmierung': typeof AuthenticatedAlarmierungRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dateien': typeof AuthenticatedDateienRoute
  '/daten-import': typeof AuthenticatedDatenImportRoute
  '/dienstplaene': typeof AuthenticatedDienstplaeneRoute
  '/einsatz-erstellen': typeof AuthenticatedEinsatzErstellenRoute
  '/hilfe': typeof AuthenticatedHilfeRoute
  '/intrahub': typeof AuthenticatedIntrahubRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/meine-einsaetze': typeof AuthenticatedMeineEinsaetzeRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/schluesselbuch': typeof AuthenticatedSchluesselbuchRoute
  '/schluesseluebergabe': typeof AuthenticatedSchluesseluebergabeRoute
  '/service-center': typeof AuthenticatedServiceCenterRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/abrechnung/$provider': typeof AuthenticatedAbrechnungProviderRouteWithChildren
  '/notdienst/lutz': typeof AuthenticatedNotdienstLutzRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/revier-center': typeof AuthenticatedRevierCenterIndexRoute
  '/abrechnung/$provider/versand': typeof AuthenticatedAbrechnungProviderVersandRoute
  '/notdienst/budeko/mitarbeiter': typeof AuthenticatedNotdienstBudekoMitarbeiterRoute
  '/notdienst/budeko/nachbearbeitung': typeof AuthenticatedNotdienstBudekoNachbearbeitungRoute
  '/notdienst/budeko/neu': typeof AuthenticatedNotdienstBudekoNeuRoute
  '/notdienst/rohrservice/mitarbeiter': typeof AuthenticatedNotdienstRohrserviceMitarbeiterRoute
  '/notdienst/rohrservice/nachbearbeitung': typeof AuthenticatedNotdienstRohrserviceNachbearbeitungRoute
  '/notdienst/rohrservice/neu': typeof AuthenticatedNotdienstRohrserviceNeuRoute
  '/revier-center/owks/nfc-punkte': typeof AuthenticatedRevierCenterOwksNfcPunkteRoute
  '/revier-center/owks/objekte': typeof AuthenticatedRevierCenterOwksObjekteRoute
  '/revier-center/owks/rundgaenge': typeof AuthenticatedRevierCenterOwksRundgaengeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/notdienst/budeko': typeof AuthenticatedNotdienstBudekoIndexRoute
  '/notdienst/rohrservice': typeof AuthenticatedNotdienstRohrserviceIndexRoute
  '/revier-center/owks': typeof AuthenticatedRevierCenterOwksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/kiehn-systeme-login': typeof KiehnSystemeLoginRoute
  '/login': typeof LoginRoute
  '/_authenticated/revier-center': typeof AuthenticatedRevierCenterRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alarmierung': typeof AuthenticatedAlarmierungRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dateien': typeof AuthenticatedDateienRoute
  '/_authenticated/daten-import': typeof AuthenticatedDatenImportRoute
  '/_authenticated/dienstplaene': typeof AuthenticatedDienstplaeneRoute
  '/_authenticated/einsatz-erstellen': typeof AuthenticatedEinsatzErstellenRoute
  '/_authenticated/hilfe': typeof AuthenticatedHilfeRoute
  '/_authenticated/intrahub': typeof AuthenticatedIntrahubRoute
  '/_authenticated/kunden': typeof AuthenticatedKundenRoute
  '/_authenticated/meine-einsaetze': typeof AuthenticatedMeineEinsaetzeRoute
  '/_authenticated/monitor': typeof AuthenticatedMonitorRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/schluesselbuch': typeof AuthenticatedSchluesselbuchRoute
  '/_authenticated/schluesseluebergabe': typeof AuthenticatedSchluesseluebergabeRoute
  '/_authenticated/service-center': typeof AuthenticatedServiceCenterRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/_authenticated/notdienst/budeko': typeof AuthenticatedNotdienstBudekoRouteRouteWithChildren
  '/_authenticated/notdienst/rohrservice': typeof AuthenticatedNotdienstRohrserviceRouteRouteWithChildren
  '/_authenticated/revier-center/owks': typeof AuthenticatedRevierCenterOwksRouteRouteWithChildren
  '/_authenticated/abrechnung/$provider': typeof AuthenticatedAbrechnungProviderRouteWithChildren
  '/_authenticated/notdienst/lutz': typeof AuthenticatedNotdienstLutzRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/_authenticated/revier-center/': typeof AuthenticatedRevierCenterIndexRoute
  '/_authenticated/abrechnung/$provider/versand': typeof AuthenticatedAbrechnungProviderVersandRoute
  '/_authenticated/notdienst/budeko/mitarbeiter': typeof AuthenticatedNotdienstBudekoMitarbeiterRoute
  '/_authenticated/notdienst/budeko/nachbearbeitung': typeof AuthenticatedNotdienstBudekoNachbearbeitungRoute
  '/_authenticated/notdienst/budeko/neu': typeof AuthenticatedNotdienstBudekoNeuRoute
  '/_authenticated/notdienst/rohrservice/mitarbeiter': typeof AuthenticatedNotdienstRohrserviceMitarbeiterRoute
  '/_authenticated/notdienst/rohrservice/nachbearbeitung': typeof AuthenticatedNotdienstRohrserviceNachbearbeitungRoute
  '/_authenticated/notdienst/rohrservice/neu': typeof AuthenticatedNotdienstRohrserviceNeuRoute
  '/_authenticated/revier-center/owks/nfc-punkte': typeof AuthenticatedRevierCenterOwksNfcPunkteRoute
  '/_authenticated/revier-center/owks/objekte': typeof AuthenticatedRevierCenterOwksObjekteRoute
  '/_authenticated/revier-center/owks/rundgaenge': typeof AuthenticatedRevierCenterOwksRundgaengeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/notdienst/budeko/': typeof AuthenticatedNotdienstBudekoIndexRoute
  '/_authenticated/notdienst/rohrservice/': typeof AuthenticatedNotdienstRohrserviceIndexRoute
  '/_authenticated/revier-center/owks/': typeof AuthenticatedRevierCenterOwksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kiehn-systeme-login'
    | '/login'
    | '/revier-center'
    | '/admin'
    | '/alarmierung'
    | '/dashboard'
    | '/dateien'
    | '/daten-import'
    | '/dienstplaene'
    | '/einsatz-erstellen'
    | '/hilfe'
    | '/intrahub'
    | '/kunden'
    | '/meine-einsaetze'
    | '/monitor'
    | '/profil'
    | '/schluesselbuch'
    | '/schluesseluebergabe'
    | '/service-center'
    | '/superadmin'
    | '/notdienst/budeko'
    | '/notdienst/rohrservice'
    | '/revier-center/owks'
    | '/abrechnung/$provider'
    | '/notdienst/lutz'
    | '/api/public/version'
    | '/revier-center/'
    | '/abrechnung/$provider/versand'
    | '/notdienst/budeko/mitarbeiter'
    | '/notdienst/budeko/nachbearbeitung'
    | '/notdienst/budeko/neu'
    | '/notdienst/rohrservice/mitarbeiter'
    | '/notdienst/rohrservice/nachbearbeitung'
    | '/notdienst/rohrservice/neu'
    | '/revier-center/owks/nfc-punkte'
    | '/revier-center/owks/objekte'
    | '/revier-center/owks/rundgaenge'
    | '/lovable/email/queue/process'
    | '/notdienst/budeko/'
    | '/notdienst/rohrservice/'
    | '/revier-center/owks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kiehn-systeme-login'
    | '/login'
    | '/admin'
    | '/alarmierung'
    | '/dashboard'
    | '/dateien'
    | '/daten-import'
    | '/dienstplaene'
    | '/einsatz-erstellen'
    | '/hilfe'
    | '/intrahub'
    | '/kunden'
    | '/meine-einsaetze'
    | '/monitor'
    | '/profil'
    | '/schluesselbuch'
    | '/schluesseluebergabe'
    | '/service-center'
    | '/superadmin'
    | '/abrechnung/$provider'
    | '/notdienst/lutz'
    | '/api/public/version'
    | '/revier-center'
    | '/abrechnung/$provider/versand'
    | '/notdienst/budeko/mitarbeiter'
    | '/notdienst/budeko/nachbearbeitung'
    | '/notdienst/budeko/neu'
    | '/notdienst/rohrservice/mitarbeiter'
    | '/notdienst/rohrservice/nachbearbeitung'
    | '/notdienst/rohrservice/neu'
    | '/revier-center/owks/nfc-punkte'
    | '/revier-center/owks/objekte'
    | '/revier-center/owks/rundgaenge'
    | '/lovable/email/queue/process'
    | '/notdienst/budeko'
    | '/notdienst/rohrservice'
    | '/revier-center/owks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kiehn-systeme-login'
    | '/login'
    | '/_authenticated/revier-center'
    | '/_authenticated/admin'
    | '/_authenticated/alarmierung'
    | '/_authenticated/dashboard'
    | '/_authenticated/dateien'
    | '/_authenticated/daten-import'
    | '/_authenticated/dienstplaene'
    | '/_authenticated/einsatz-erstellen'
    | '/_authenticated/hilfe'
    | '/_authenticated/intrahub'
    | '/_authenticated/kunden'
    | '/_authenticated/meine-einsaetze'
    | '/_authenticated/monitor'
    | '/_authenticated/profil'
    | '/_authenticated/schluesselbuch'
    | '/_authenticated/schluesseluebergabe'
    | '/_authenticated/service-center'
    | '/_authenticated/superadmin'
    | '/_authenticated/notdienst/budeko'
    | '/_authenticated/notdienst/rohrservice'
    | '/_authenticated/revier-center/owks'
    | '/_authenticated/abrechnung/$provider'
    | '/_authenticated/notdienst/lutz'
    | '/api/public/version'
    | '/_authenticated/revier-center/'
    | '/_authenticated/abrechnung/$provider/versand'
    | '/_authenticated/notdienst/budeko/mitarbeiter'
    | '/_authenticated/notdienst/budeko/nachbearbeitung'
    | '/_authenticated/notdienst/budeko/neu'
    | '/_authenticated/notdienst/rohrservice/mitarbeiter'
    | '/_authenticated/notdienst/rohrservice/nachbearbeitung'
    | '/_authenticated/notdienst/rohrservice/neu'
    | '/_authenticated/revier-center/owks/nfc-punkte'
    | '/_authenticated/revier-center/owks/objekte'
    | '/_authenticated/revier-center/owks/rundgaenge'
    | '/lovable/email/queue/process'
    | '/_authenticated/notdienst/budeko/'
    | '/_authenticated/notdienst/rohrservice/'
    | '/_authenticated/revier-center/owks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KiehnSystemeLoginRoute: typeof KiehnSystemeLoginRoute
  LoginRoute: typeof LoginRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiehn-systeme-login': {
      id: '/kiehn-systeme-login'
      path: '/kiehn-systeme-login'
      fullPath: '/kiehn-systeme-login'
      preLoaderRoute: typeof KiehnSystemeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-center': {
      id: '/_authenticated/service-center'
      path: '/service-center'
      fullPath: '/service-center'
      preLoaderRoute: typeof AuthenticatedServiceCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schluesseluebergabe': {
      id: '/_authenticated/schluesseluebergabe'
      path: '/schluesseluebergabe'
      fullPath: '/schluesseluebergabe'
      preLoaderRoute: typeof AuthenticatedSchluesseluebergabeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schluesselbuch': {
      id: '/_authenticated/schluesselbuch'
      path: '/schluesselbuch'
      fullPath: '/schluesselbuch'
      preLoaderRoute: typeof AuthenticatedSchluesselbuchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitor': {
      id: '/_authenticated/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AuthenticatedMonitorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meine-einsaetze': {
      id: '/_authenticated/meine-einsaetze'
      path: '/meine-einsaetze'
      fullPath: '/meine-einsaetze'
      preLoaderRoute: typeof AuthenticatedMeineEinsaetzeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kunden': {
      id: '/_authenticated/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof AuthenticatedKundenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intrahub': {
      id: '/_authenticated/intrahub'
      path: '/intrahub'
      fullPath: '/intrahub'
      preLoaderRoute: typeof AuthenticatedIntrahubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hilfe': {
      id: '/_authenticated/hilfe'
      path: '/hilfe'
      fullPath: '/hilfe'
      preLoaderRoute: typeof AuthenticatedHilfeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/einsatz-erstellen': {
      id: '/_authenticated/einsatz-erstellen'
      path: '/einsatz-erstellen'
      fullPath: '/einsatz-erstellen'
      preLoaderRoute: typeof AuthenticatedEinsatzErstellenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dienstplaene': {
      id: '/_authenticated/dienstplaene'
      path: '/dienstplaene'
      fullPath: '/dienstplaene'
      preLoaderRoute: typeof AuthenticatedDienstplaeneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daten-import': {
      id: '/_authenticated/daten-import'
      path: '/daten-import'
      fullPath: '/daten-import'
      preLoaderRoute: typeof AuthenticatedDatenImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dateien': {
      id: '/_authenticated/dateien'
      path: '/dateien'
      fullPath: '/dateien'
      preLoaderRoute: typeof AuthenticatedDateienRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alarmierung': {
      id: '/_authenticated/alarmierung'
      path: '/alarmierung'
      fullPath: '/alarmierung'
      preLoaderRoute: typeof AuthenticatedAlarmierungRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revier-center': {
      id: '/_authenticated/revier-center'
      path: '/revier-center'
      fullPath: '/revier-center'
      preLoaderRoute: typeof AuthenticatedRevierCenterRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revier-center/': {
      id: '/_authenticated/revier-center/'
      path: '/'
      fullPath: '/revier-center/'
      preLoaderRoute: typeof AuthenticatedRevierCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRevierCenterRouteRoute
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notdienst/lutz': {
      id: '/_authenticated/notdienst/lutz'
      path: '/notdienst/lutz'
      fullPath: '/notdienst/lutz'
      preLoaderRoute: typeof AuthenticatedNotdienstLutzRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/abrechnung/$provider': {
      id: '/_authenticated/abrechnung/$provider'
      path: '/abrechnung/$provider'
      fullPath: '/abrechnung/$provider'
      preLoaderRoute: typeof AuthenticatedAbrechnungProviderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revier-center/owks': {
      id: '/_authenticated/revier-center/owks'
      path: '/owks'
      fullPath: '/revier-center/owks'
      preLoaderRoute: typeof AuthenticatedRevierCenterOwksRouteRouteImport
      parentRoute: typeof AuthenticatedRevierCenterRouteRoute
    }
    '/_authenticated/notdienst/rohrservice': {
      id: '/_authenticated/notdienst/rohrservice'
      path: '/notdienst/rohrservice'
      fullPath: '/notdienst/rohrservice'
      preLoaderRoute: typeof AuthenticatedNotdienstRohrserviceRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notdienst/budeko': {
      id: '/_authenticated/notdienst/budeko'
      path: '/notdienst/budeko'
      fullPath: '/notdienst/budeko'
      preLoaderRoute: typeof AuthenticatedNotdienstBudekoRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revier-center/owks/': {
      id: '/_authenticated/revier-center/owks/'
      path: '/'
      fullPath: '/revier-center/owks/'
      preLoaderRoute: typeof AuthenticatedRevierCenterOwksIndexRouteImport
      parentRoute: typeof AuthenticatedRevierCenterOwksRouteRoute
    }
    '/_authenticated/notdienst/rohrservice/': {
      id: '/_authenticated/notdienst/rohrservice/'
      path: '/'
      fullPath: '/notdienst/rohrservice/'
      preLoaderRoute: typeof AuthenticatedNotdienstRohrserviceIndexRouteImport
      parentRoute: typeof AuthenticatedNotdienstRohrserviceRouteRoute
    }
    '/_authenticated/notdienst/budeko/': {
      id: '/_authenticated/notdienst/budeko/'
      path: '/'
      fullPath: '/notdienst/budeko/'
      preLoaderRoute: typeof AuthenticatedNotdienstBudekoIndexRouteImport
      parentRoute: typeof AuthenticatedNotdienstBudekoRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/revier-center/owks/rundgaenge': {
      id: '/_authenticated/revier-center/owks/rundgaenge'
      path: '/rundgaenge'
      fullPath: '/revier-center/owks/rundgaenge'
      preLoaderRoute: typeof AuthenticatedRevierCenterOwksRundgaengeRouteImport
      parentRoute: typeof AuthenticatedRevierCenterOwksRouteRoute
    }
    '/_authenticated/revier-center/owks/objekte': {
      id: '/_authenticated/revier-center/owks/objekte'
      path: '/objekte'
      fullPath: '/revier-center/owks/objekte'
      preLoaderRoute: typeof AuthenticatedRevierCenterOwksObjekteRouteImport
      parentRoute: typeof AuthenticatedRevierCenterOwksRouteRoute
    }
    '/_authenticated/revier-center/owks/nfc-punkte': {
      id: '/_authenticated/revier-center/owks/nfc-punkte'
      path: '/nfc-punkte'
      fullPath: '/revier-center/owks/nfc-punkte'
      preLoaderRoute: typeof AuthenticatedRevierCenterOwksNfcPunkteRouteImport
      parentRoute: typeof AuthenticatedRevierCenterOwksRouteRoute
    }
    '/_authenticated/notdienst/rohrservice/neu': {
      id: '/_authenticated/notdienst/rohrservice/neu'
      path: '/neu'
      fullPath: '/notdienst/rohrservice/neu'
      preLoaderRoute: typeof AuthenticatedNotdienstRohrserviceNeuRouteImport
      parentRoute: typeof AuthenticatedNotdienstRohrserviceRouteRoute
    }
    '/_authenticated/notdienst/rohrservice/nachbearbeitung': {
      id: '/_authenticated/notdienst/rohrservice/nachbearbeitung'
      path: '/nachbearbeitung'
      fullPath: '/notdienst/rohrservice/nachbearbeitung'
      preLoaderRoute: typeof AuthenticatedNotdienstRohrserviceNachbearbeitungRouteImport
      parentRoute: typeof AuthenticatedNotdienstRohrserviceRouteRoute
    }
    '/_authenticated/notdienst/rohrservice/mitarbeiter': {
      id: '/_authenticated/notdienst/rohrservice/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/notdienst/rohrservice/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedNotdienstRohrserviceMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedNotdienstRohrserviceRouteRoute
    }
    '/_authenticated/notdienst/budeko/neu': {
      id: '/_authenticated/notdienst/budeko/neu'
      path: '/neu'
      fullPath: '/notdienst/budeko/neu'
      preLoaderRoute: typeof AuthenticatedNotdienstBudekoNeuRouteImport
      parentRoute: typeof AuthenticatedNotdienstBudekoRouteRoute
    }
    '/_authenticated/notdienst/budeko/nachbearbeitung': {
      id: '/_authenticated/notdienst/budeko/nachbearbeitung'
      path: '/nachbearbeitung'
      fullPath: '/notdienst/budeko/nachbearbeitung'
      preLoaderRoute: typeof AuthenticatedNotdienstBudekoNachbearbeitungRouteImport
      parentRoute: typeof AuthenticatedNotdienstBudekoRouteRoute
    }
    '/_authenticated/notdienst/budeko/mitarbeiter': {
      id: '/_authenticated/notdienst/budeko/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/notdienst/budeko/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedNotdienstBudekoMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedNotdienstBudekoRouteRoute
    }
    '/_authenticated/abrechnung/$provider/versand': {
      id: '/_authenticated/abrechnung/$provider/versand'
      path: '/versand'
      fullPath: '/abrechnung/$provider/versand'
      preLoaderRoute: typeof AuthenticatedAbrechnungProviderVersandRouteImport
      parentRoute: typeof AuthenticatedAbrechnungProviderRoute
    }
  }
}

interface AuthenticatedRevierCenterOwksRouteRouteChildren {
  AuthenticatedRevierCenterOwksNfcPunkteRoute: typeof AuthenticatedRevierCenterOwksNfcPunkteRoute
  AuthenticatedRevierCenterOwksObjekteRoute: typeof AuthenticatedRevierCenterOwksObjekteRoute
  AuthenticatedRevierCenterOwksRundgaengeRoute: typeof AuthenticatedRevierCenterOwksRundgaengeRoute
  AuthenticatedRevierCenterOwksIndexRoute: typeof AuthenticatedRevierCenterOwksIndexRoute
}

const AuthenticatedRevierCenterOwksRouteRouteChildren: AuthenticatedRevierCenterOwksRouteRouteChildren =
  {
    AuthenticatedRevierCenterOwksNfcPunkteRoute:
      AuthenticatedRevierCenterOwksNfcPunkteRoute,
    AuthenticatedRevierCenterOwksObjekteRoute:
      AuthenticatedRevierCenterOwksObjekteRoute,
    AuthenticatedRevierCenterOwksRundgaengeRoute:
      AuthenticatedRevierCenterOwksRundgaengeRoute,
    AuthenticatedRevierCenterOwksIndexRoute:
      AuthenticatedRevierCenterOwksIndexRoute,
  }

const AuthenticatedRevierCenterOwksRouteRouteWithChildren =
  AuthenticatedRevierCenterOwksRouteRoute._addFileChildren(
    AuthenticatedRevierCenterOwksRouteRouteChildren,
  )

interface AuthenticatedRevierCenterRouteRouteChildren {
  AuthenticatedRevierCenterOwksRouteRoute: typeof AuthenticatedRevierCenterOwksRouteRouteWithChildren
  AuthenticatedRevierCenterIndexRoute: typeof AuthenticatedRevierCenterIndexRoute
}

const AuthenticatedRevierCenterRouteRouteChildren: AuthenticatedRevierCenterRouteRouteChildren =
  {
    AuthenticatedRevierCenterOwksRouteRoute:
      AuthenticatedRevierCenterOwksRouteRouteWithChildren,
    AuthenticatedRevierCenterIndexRoute: AuthenticatedRevierCenterIndexRoute,
  }

const AuthenticatedRevierCenterRouteRouteWithChildren =
  AuthenticatedRevierCenterRouteRoute._addFileChildren(
    AuthenticatedRevierCenterRouteRouteChildren,
  )

interface AuthenticatedNotdienstBudekoRouteRouteChildren {
  AuthenticatedNotdienstBudekoMitarbeiterRoute: typeof AuthenticatedNotdienstBudekoMitarbeiterRoute
  AuthenticatedNotdienstBudekoNachbearbeitungRoute: typeof AuthenticatedNotdienstBudekoNachbearbeitungRoute
  AuthenticatedNotdienstBudekoNeuRoute: typeof AuthenticatedNotdienstBudekoNeuRoute
  AuthenticatedNotdienstBudekoIndexRoute: typeof AuthenticatedNotdienstBudekoIndexRoute
}

const AuthenticatedNotdienstBudekoRouteRouteChildren: AuthenticatedNotdienstBudekoRouteRouteChildren =
  {
    AuthenticatedNotdienstBudekoMitarbeiterRoute:
      AuthenticatedNotdienstBudekoMitarbeiterRoute,
    AuthenticatedNotdienstBudekoNachbearbeitungRoute:
      AuthenticatedNotdienstBudekoNachbearbeitungRoute,
    AuthenticatedNotdienstBudekoNeuRoute: AuthenticatedNotdienstBudekoNeuRoute,
    AuthenticatedNotdienstBudekoIndexRoute:
      AuthenticatedNotdienstBudekoIndexRoute,
  }

const AuthenticatedNotdienstBudekoRouteRouteWithChildren =
  AuthenticatedNotdienstBudekoRouteRoute._addFileChildren(
    AuthenticatedNotdienstBudekoRouteRouteChildren,
  )

interface AuthenticatedNotdienstRohrserviceRouteRouteChildren {
  AuthenticatedNotdienstRohrserviceMitarbeiterRoute: typeof AuthenticatedNotdienstRohrserviceMitarbeiterRoute
  AuthenticatedNotdienstRohrserviceNachbearbeitungRoute: typeof AuthenticatedNotdienstRohrserviceNachbearbeitungRoute
  AuthenticatedNotdienstRohrserviceNeuRoute: typeof AuthenticatedNotdienstRohrserviceNeuRoute
  AuthenticatedNotdienstRohrserviceIndexRoute: typeof AuthenticatedNotdienstRohrserviceIndexRoute
}

const AuthenticatedNotdienstRohrserviceRouteRouteChildren: AuthenticatedNotdienstRohrserviceRouteRouteChildren =
  {
    AuthenticatedNotdienstRohrserviceMitarbeiterRoute:
      AuthenticatedNotdienstRohrserviceMitarbeiterRoute,
    AuthenticatedNotdienstRohrserviceNachbearbeitungRoute:
      AuthenticatedNotdienstRohrserviceNachbearbeitungRoute,
    AuthenticatedNotdienstRohrserviceNeuRoute:
      AuthenticatedNotdienstRohrserviceNeuRoute,
    AuthenticatedNotdienstRohrserviceIndexRoute:
      AuthenticatedNotdienstRohrserviceIndexRoute,
  }

const AuthenticatedNotdienstRohrserviceRouteRouteWithChildren =
  AuthenticatedNotdienstRohrserviceRouteRoute._addFileChildren(
    AuthenticatedNotdienstRohrserviceRouteRouteChildren,
  )

interface AuthenticatedAbrechnungProviderRouteChildren {
  AuthenticatedAbrechnungProviderVersandRoute: typeof AuthenticatedAbrechnungProviderVersandRoute
}

const AuthenticatedAbrechnungProviderRouteChildren: AuthenticatedAbrechnungProviderRouteChildren =
  {
    AuthenticatedAbrechnungProviderVersandRoute:
      AuthenticatedAbrechnungProviderVersandRoute,
  }

const AuthenticatedAbrechnungProviderRouteWithChildren =
  AuthenticatedAbrechnungProviderRoute._addFileChildren(
    AuthenticatedAbrechnungProviderRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedRevierCenterRouteRoute: typeof AuthenticatedRevierCenterRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlarmierungRoute: typeof AuthenticatedAlarmierungRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDateienRoute: typeof AuthenticatedDateienRoute
  AuthenticatedDatenImportRoute: typeof AuthenticatedDatenImportRoute
  AuthenticatedDienstplaeneRoute: typeof AuthenticatedDienstplaeneRoute
  AuthenticatedEinsatzErstellenRoute: typeof AuthenticatedEinsatzErstellenRoute
  AuthenticatedHilfeRoute: typeof AuthenticatedHilfeRoute
  AuthenticatedIntrahubRoute: typeof AuthenticatedIntrahubRoute
  AuthenticatedKundenRoute: typeof AuthenticatedKundenRoute
  AuthenticatedMeineEinsaetzeRoute: typeof AuthenticatedMeineEinsaetzeRoute
  AuthenticatedMonitorRoute: typeof AuthenticatedMonitorRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedSchluesselbuchRoute: typeof AuthenticatedSchluesselbuchRoute
  AuthenticatedSchluesseluebergabeRoute: typeof AuthenticatedSchluesseluebergabeRoute
  AuthenticatedServiceCenterRoute: typeof AuthenticatedServiceCenterRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedNotdienstBudekoRouteRoute: typeof AuthenticatedNotdienstBudekoRouteRouteWithChildren
  AuthenticatedNotdienstRohrserviceRouteRoute: typeof AuthenticatedNotdienstRohrserviceRouteRouteWithChildren
  AuthenticatedAbrechnungProviderRoute: typeof AuthenticatedAbrechnungProviderRouteWithChildren
  AuthenticatedNotdienstLutzRoute: typeof AuthenticatedNotdienstLutzRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRevierCenterRouteRoute:
    AuthenticatedRevierCenterRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlarmierungRoute: AuthenticatedAlarmierungRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDateienRoute: AuthenticatedDateienRoute,
  AuthenticatedDatenImportRoute: AuthenticatedDatenImportRoute,
  AuthenticatedDienstplaeneRoute: AuthenticatedDienstplaeneRoute,
  AuthenticatedEinsatzErstellenRoute: AuthenticatedEinsatzErstellenRoute,
  AuthenticatedHilfeRoute: AuthenticatedHilfeRoute,
  AuthenticatedIntrahubRoute: AuthenticatedIntrahubRoute,
  AuthenticatedKundenRoute: AuthenticatedKundenRoute,
  AuthenticatedMeineEinsaetzeRoute: AuthenticatedMeineEinsaetzeRoute,
  AuthenticatedMonitorRoute: AuthenticatedMonitorRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedSchluesselbuchRoute: AuthenticatedSchluesselbuchRoute,
  AuthenticatedSchluesseluebergabeRoute: AuthenticatedSchluesseluebergabeRoute,
  AuthenticatedServiceCenterRoute: AuthenticatedServiceCenterRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedNotdienstBudekoRouteRoute:
    AuthenticatedNotdienstBudekoRouteRouteWithChildren,
  AuthenticatedNotdienstRohrserviceRouteRoute:
    AuthenticatedNotdienstRohrserviceRouteRouteWithChildren,
  AuthenticatedAbrechnungProviderRoute:
    AuthenticatedAbrechnungProviderRouteWithChildren,
  AuthenticatedNotdienstLutzRoute: AuthenticatedNotdienstLutzRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KiehnSystemeLoginRoute: KiehnSystemeLoginRoute,
  LoginRoute: LoginRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
